# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow7.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 350, 90, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 240, 141, 16))
        self.label.setObjectName("label")
        self.lnCogn = QtWidgets.QLineEdit(self.centralwidget)
        self.lnCogn.setGeometry(QtCore.QRect(60, 40, 113, 28))
        self.lnCogn.setObjectName("lnCogn")
        self.lnNome = QtWidgets.QLineEdit(self.centralwidget)
        self.lnNome.setGeometry(QtCore.QRect(60, 100, 113, 28))
        self.lnNome.setObjectName("lnNome")
        self.lnSesso = QtWidgets.QLineEdit(self.centralwidget)
        self.lnSesso.setGeometry(QtCore.QRect(60, 150, 113, 28))
        self.lnSesso.setObjectName("lnSesso")
        self.lnLuogo = QtWidgets.QLineEdit(self.centralwidget)
        self.lnLuogo.setGeometry(QtCore.QRect(60, 270, 113, 28))
        self.lnLuogo.setObjectName("lnLuogo")
        self.dataNas = QtWidgets.QDateEdit(self.centralwidget)
        self.dataNas.setGeometry(QtCore.QRect(60, 200, 111, 21))
        self.dataNas.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dataNas.setCalendarPopup(True)
        self.dataNas.setObjectName("dataNas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "&Ok"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
